/**
 * Write Prover.toml for the Coinbase circuits, from the real attestation.
 *
 * `Prover.toml` is gitignored -- it holds witness data -- so it is never
 * committed, was not in the 2026-08-31 backup, and did not survive the machine
 * move. Nothing about it was irreplaceable: the attestation transaction is on
 * Base forever, and the one thing that has to be produced fresh is a signature
 * from the attested wallet, whose key is in `.env.test` as ATTESTATION_KEY.
 * This script is how it gets rebuilt, instead of by hand.
 *
 *   npx tsx scripts/gen-prover-toml.ts
 *
 * Reads ATTESTATION_KEY from .env.test. Writes into the sibling circuits
 * checkout, which is where `scripts/build.sh` looks.
 */
import { ethers } from 'ethers';
import fs from 'node:fs';
import path from 'node:path';
import { computeCircuitParams } from '../src/input/inputBuilder.js';
import {
  computeSignalHash,
  computeScope,
  computeNullifier,
  computeWalletNullifier,
  splitSignatureToBytes,
  hexToBytes,
  padBytes,
  buildPaddedMerkleProof,
  encodeCountryList,
} from '../src/input/inputBuilder.js';
import { CIRCUIT_IDS } from '../src/config/circuitIds.js';

const EAS_GRAPHQL = process.env.EAS_GRAPHQL_ENDPOINT || 'https://base.easscan.org/graphql';
const RPC_URLS = (process.env.BASE_RPC_URL || 'https://mainnet.base.org').split(',');
const SCOPE = 'proofport';
const CIRCUITS_DIR = path.resolve(process.cwd(), '..', 'circuits');

function attestationKey(): string {
  const file = path.resolve(process.cwd(), '.env.test');
  const line = fs
    .readFileSync(file, 'utf8')
    .split('\n')
    .find((l) => l.startsWith('ATTESTATION_KEY='));
  if (!line) throw new Error('ATTESTATION_KEY is not in .env.test');
  return line.slice('ATTESTATION_KEY='.length).trim().replace(/^["']|["']$/g, '');
}

const list = (name: string, values: readonly (number | string)[]) =>
  `${name} = [${values.join(', ')}]`;

/**
 * A TOML array of arrays, from a flat list.
 *
 * The circuit takes these as fixed nested shapes -- the Merkle proof is
 * [[u8;32];8], the country list [[u8;2];10] -- and the builders in
 * inputBuilder.ts hand back one flat sequence, because that is what bb's
 * positional input list wants. Writing the flat sequence into Prover.toml
 * fails with "cannot parse value Integer(85) into Array", which names the
 * value and not the shape, so the row width has to be right here.
 */
function nested(name: string, flat: string[], width: number): string {
  const out: string[] = [];
  for (let i = 0; i < flat.length; i += width) {
    out.push(`  [${flat.slice(i, i + width).join(', ')}]`);
  }
  return `${name} = [\n${out.join(',\n')},\n]`;
}

async function main() {
  const wallet = new ethers.Wallet(attestationKey());
  console.log(`  attested wallet: ${wallet.address}`);

  // ── coinbase_attestation: the wallet signs signal_hash, EIP-191 ───────────
  const kycId = CIRCUIT_IDS.COINBASE_ATTESTATION;
  const kycSignal = computeSignalHash(wallet.address, SCOPE, kycId);
  const kycSignature = await wallet.signMessage(kycSignal);

  const params = await computeCircuitParams(
    { address: wallet.address, signature: kycSignature, scope: SCOPE, circuitId: kycId },
    EAS_GRAPHQL,
    RPC_URLS,
  );
  console.log(`  attestation tx: ${params.txLength} bytes, attester in signer list`);

  const merkleProofRows = buildPaddedMerkleProof(params.merkleProof, params.merkleDepth);
  const shared = [
    list('signer_list_merkle_root', hexToBytes(params.merkleRoot)),
    list('scope', Array.from(params.scopeBytes)),
  ];
  const privateTail = (signature: string) => [
    list('user_address', hexToBytes(params.userAddress)),
    list('user_signature', splitSignatureToBytes(signature)),
    list('user_pubkey_x', hexToBytes(params.userPubkeyX)),
    list('user_pubkey_y', hexToBytes(params.userPubkeyY)),
    list('raw_transaction', padBytes(Array.from(params.rawTxBytes), 300)),
    `tx_length = ${params.txLength}`,
    list('coinbase_attester_pubkey_x', hexToBytes(params.attesterPubkeyX)),
    list('coinbase_attester_pubkey_y', hexToBytes(params.attesterPubkeyY)),
    nested('coinbase_signer_merkle_proof', merkleProofRows, 32),
    `coinbase_signer_leaf_index = ${params.merkleLeafIndex}`,
    `merkle_proof_depth = ${params.merkleDepth}`,
  ];

  const header = (circuit: string) =>
    [
      '# Auto-generated by proofport-ai/scripts/gen-prover-toml.ts.',
      `# Circuit: ${circuit}. Real Coinbase attestation for ${wallet.address}.`,
      '# Regenerate rather than edit: this file is gitignored and does not',
      '# survive a machine move.',
      '',
      '# ============ Public Inputs ============',
    ].join('\n');

  {
    const body = [
      header(kycId),
      list('signal_hash', Array.from(kycSignal)),
      ...shared,
      list('nullifier', Array.from(params.nullifierBytes)),
      '',
      '# ============ Private Inputs ============',
      ...privateTail(kycSignature),
      '',
    ].join('\n');
    const out = path.join(CIRCUITS_DIR, 'coinbase-attestation', 'Prover.toml');
    fs.writeFileSync(out, body);
    console.log(`  wrote ${out}`);
  }

  // ── coinbase_country_attestation: same wallet, a different schema ─────────
  //
  // The country circuit reads a SEPARATE EAS attestation (its own schemaId),
  // so this is a second fetch rather than a reshaping of the first. It also
  // takes the country list and the inclusion flag as public inputs, between
  // the Merkle root and the scope -- an order the flat list below has to match.
  {
    const countryId = CIRCUIT_IDS.COINBASE_COUNTRY_ATTESTATION;
    const countryList = ['US', 'KR'];
    const isIncluded = true;

    const signal = computeSignalHash(wallet.address, SCOPE, countryId);
    const signature = await wallet.signMessage(signal);
    const cp = await computeCircuitParams(
      {
        address: wallet.address,
        signature,
        scope: SCOPE,
        circuitId: countryId,
        countryList,
        isIncluded,
      },
      EAS_GRAPHQL,
      RPC_URLS,
    );
    console.log(`  country attestation tx: ${cp.txLength} bytes`);

    const rows = buildPaddedMerkleProof(cp.merkleProof, cp.merkleDepth);
    const body = [
      header(countryId),
      list('signal_hash', Array.from(signal)),
      list('signer_list_merkle_root', hexToBytes(cp.merkleRoot)),
      nested('country_list', encodeCountryList(countryList), 2),
      `country_list_length = ${countryList.length}`,
      `is_included = ${isIncluded}`,
      list('scope', Array.from(cp.scopeBytes)),
      list('nullifier', Array.from(cp.nullifierBytes)),
      '',
      '# ============ Private Inputs ============',
      list('user_address', hexToBytes(cp.userAddress)),
      list('user_signature', splitSignatureToBytes(signature)),
      list('user_pubkey_x', hexToBytes(cp.userPubkeyX)),
      list('user_pubkey_y', hexToBytes(cp.userPubkeyY)),
      list('raw_transaction', padBytes(Array.from(cp.rawTxBytes), 300)),
      `tx_length = ${cp.txLength}`,
      list('coinbase_attester_pubkey_x', hexToBytes(cp.attesterPubkeyX)),
      list('coinbase_attester_pubkey_y', hexToBytes(cp.attesterPubkeyY)),
      nested('coinbase_signer_merkle_proof', rows, 32),
      `coinbase_signer_leaf_index = ${cp.merkleLeafIndex}`,
      `merkle_proof_depth = ${cp.merkleDepth}`,
      '',
    ].join('\n');
    const out = path.join(CIRCUITS_DIR, 'coinbase-country-attestation', 'Prover.toml');
    fs.writeFileSync(out, body);
    console.log(`  wrote ${out}`);
  }

  // ── arc_eligibility: two fixtures, because the circuit has two modes ─────
  //
  // With an action the wallet signs EIP-712 typed data and `signal_hash` goes
  // out as zeros; without one it personal_signs `signal_hash` and the EIP-712
  // pair goes out as zeros. The circuit refuses a fixture that fills both, so
  // the old single fixture -- a real signal hash AND an action -- no longer
  // executes.
  //
  // The nullifier comes from the wallet and a constant compiled into the
  // circuit, not from `signal_hash`: that value is zero in action mode, so
  // deriving from it would give one wallet two identities in one scope.
  {
    const arcId = 'arc_eligibility';
    const signal = computeSignalHash(wallet.address, SCOPE, arcId);
    const scopeBytes = computeScope(SCOPE);
    const nullifier = computeWalletNullifier(wallet.address, arcId, scopeBytes);
    const EMPTY_32 = new Uint8Array(32);

    const domain = {
      name: 'ArcVault',
      version: '1',
      chainId: 5042002,
      verifyingContract: '0x1234567890123456789012345678901234567890',
    };
    const types = {
      Deposit: [
        { name: 'amount', type: 'uint256' },
        { name: 'nonce', type: 'uint256' },
        { name: 'expiry', type: 'uint64' },
      ],
    };
    const message = { amount: 10_000_000n, nonce: 1n, expiry: 1_789_000_000n };
    const signature = await wallet.signTypedData(domain, types, message);

    const withAction = [
      header(arcId),
      list('signal_hash', Array.from(EMPTY_32)),
      list('domain_separator', Array.from(ethers.getBytes(ethers.TypedDataEncoder.hashDomain(domain)))),
      list('action_hash', Array.from(ethers.getBytes(ethers.TypedDataEncoder.hashStruct('Deposit', types, message)))),
      ...shared,
      list('nullifier', Array.from(nullifier)),
      '',
      '# ============ Private Inputs ============',
      ...privateTail(signature),
      '',
    ].join('\n');
    const out = path.join(CIRCUITS_DIR, 'arc-eligibility', 'Prover.toml');
    fs.writeFileSync(out, withAction);
    console.log(`  wrote ${out}`);

    // The same wallet and scope with no action: the EIP-712 pair is empty and
    // the wallet personal_signs the challenge. The nullifier is byte for byte
    // the one above, which is the property worth checking.
    const signalSignature = await wallet.signMessage(signal);
    const noAction = [
      header(arcId),
      list('signal_hash', Array.from(signal)),
      list('domain_separator', Array.from(EMPTY_32)),
      list('action_hash', Array.from(EMPTY_32)),
      ...shared,
      list('nullifier', Array.from(nullifier)),
      '',
      '# ============ Private Inputs ============',
      ...privateTail(signalSignature),
      '',
    ].join('\n');
    const outNoAction = path.join(CIRCUITS_DIR, 'arc-eligibility', 'Prover.no-action.toml');
    fs.writeFileSync(outNoAction, noAction);
    console.log(`  wrote ${outNoAction}`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
